version: "3.8"

services:
  consumer:
    build:
      context: ./ConsumerService
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: admin
      RABBIT_PASS: password
      POSTGRES_HOST: postgresdb
      POSTGRES_USER: admin
      POSTGRES_DB: clew_medical
      POSTGRES_PASSWORD: password
      POSTGRES_TABLE: events
      WEB_ADDR: 0.0.0.0
      WEB_PORT: 8000
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq

  publisher:
    build:
      context: ./PublisherService
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: admin
      RABBIT_PASS: password
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8.1-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672

  postgresdb:
    image: postgres:12.0
    container_name: postgresdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: clew_medical
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
volumes:
  pgdata:
    external: true